---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${{values.owner}}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${{values.owner}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
